import Head from 'next/head'
import Nav from './components/Nav'
import Header from './components/Header'
import Footer from './components/Footer'
import Projects from './components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Amalia Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <Projects />
      <Footer />
    </div>
  )
}
